// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9n35eQz37vKHQeuCHXPHwo
// Component: 5vQjPW3bqMuqP
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header2 from "../../Header2" // plasmic-import: k7o7R5KA05BDU1/component
import Button from "../../Button" // plasmic-import: FThbuefNiac0C/component
import Testimonial from "../../Testimonial" // plasmic-import: D0Z3blg4Fokcn/component
import BlogPosts from "../../BlogPosts" // plasmic-import: D0lgpUsdZ2nSN/component
import CtaBlock from "../../CtaBlock" // plasmic-import: Wi4fdgLEBvNwe/component
import HeroSection from "../../HeroSection" // plasmic-import: -OzwMuddIFsAXB/component
import Footer from "../../Footer" // plasmic-import: UCdzYIWgs-f8ml/component
import { useScreenVariants as useScreenVariantsj0Zyv8Tr7BOtZ2 } from "./PlasmicGlobalVariant__Screen" // plasmic-import: j0Zyv8Tr7BOtZ2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_saa_s_website.module.css" // plasmic-import: 9n35eQz37vKHQeuCHXPHwo/projectcss
import * as sty from "./PlasmicHomepage.module.css" // plasmic-import: 5vQjPW3bqMuqP/css
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg" // plasmic-import: S5xRGvVGtklZAi/icon
import corinneKutzTMi2R5NfoUnsplashjpgXcdVvFVkT2X8J6 from "./images/corinneKutzTMi2R5NfoUnsplashjpg.jpeg" // plasmic-import: xcdVvFVkT2X8J6/picture
import tiffanyTertipesNxcs8Wwj9J0Unsplashjpg7YXw56Ww6R9OSh from "./images/tiffanyTertipesNxcs8Wwj9J0Unsplashjpg.jpeg" // plasmic-import: 7YXw56Ww6R9oSh/picture
import xpsOcAuPlfZxEcUnsplashjpgILfqgGwTm1KB from "./images/xpsOcAuPlfZxEcUnsplashjpg.jpeg" // plasmic-import: iLFQGGw-TM1K-B/picture
import mepngKNmo8AmFIoYx9Z from "./images/mepng.png" // plasmic-import: kNMO8amFIoYX9z/picture
import thumbAvatar1583758683JpgJc4NK1H4FWikX from "./images/thumbAvatar1583758683Jpg.jpeg" // plasmic-import: Jc4nK1H4fWikX-/picture

export const PlasmicHomepage__VariantProps = new Array()

export const PlasmicHomepage__ArgProps = new Array()

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const $ctx = ph.useDataEnv?.() || {}
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args])
  const $props = args
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsj0Zyv8Tr7BOtZ2(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              sty.root
            )}
          >
            <div className={classNames(projectcss.all, sty.freeBox__sxrGe)}>
              <div className={classNames(projectcss.all, sty.freeBox__fhfL2)}>
                <Header2
                  data-plasmic-name={"header2"}
                  data-plasmic-override={overrides.header2}
                  className={classNames("__wab_instance", sty.header2)}
                />

                <div className={classNames(projectcss.all, sty.freeBox__qMzyf)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__gjB7K)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__m9AnD)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___4V5Ki
                        )}
                      >
                        <h1
                          data-plasmic-name={"h1"}
                          data-plasmic-override={overrides.h1}
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Ready to accept or acquiesce willing."
                            : "Hero for your SaaS landing page."}
                        </h1>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kvOys
                          )}
                        >
                          {
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut ."
                          }
                        </div>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__tveTt
                          )}
                          endIcon={
                            <ArrowRightsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__bvwY
                              )}
                              role={"img"}
                            />
                          }
                        >
                          {"Get started"}
                        </Button>
                      </p.Stack>
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__hzedD)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___1D7Dy
                        )}
                      />
                    </div>
                  </p.Stack>
                </div>
              </div>
            </div>

            {true ? (
              <section
                data-plasmic-name={"features"}
                data-plasmic-override={overrides.features}
                className={classNames(projectcss.all, sty.features)}
              >
                <div className={classNames(projectcss.all, sty.column__mFlig)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__uxNh
                    )}
                  >
                    {"Value propositions headline."}
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ypVgS
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                    }
                  </div>

                  <div
                    data-plasmic-name={"container4"}
                    data-plasmic-override={overrides.container4}
                    className={classNames(projectcss.all, sty.container4)}
                  >
                    <div
                      data-plasmic-name={"outerRow2"}
                      data-plasmic-override={overrides.outerRow2}
                      className={classNames(projectcss.all, sty.outerRow2)}
                    >
                      <div
                        data-plasmic-name={"row2"}
                        data-plasmic-override={overrides.row2}
                        className={classNames(projectcss.all, sty.row2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__eJ8TS
                          )}
                        >
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__dSrN
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__dHjw
                                )}
                              />

                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__cZi6O
                                )}
                              >
                                {"Some value proposition of your service."}
                              </h3>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ktpxb
                                )}
                              >
                                {
                                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                                }
                              </div>

                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button__rouk3
                                )}
                                color={"blue"}
                                endIcon={
                                  <ArrowRightsvgIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg___0OluR
                                    )}
                                    role={"img"}
                                  />
                                }
                                shape={"rounded"}
                                showEndIcon={true}
                              >
                                {"Learn more"}
                              </Button>
                            </p.Stack>
                          ) : null}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__w2SLd
                          )}
                        >
                          {true ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__gU0Yh
                              )}
                            >
                              <p.PlasmicImg
                                alt={""}
                                className={classNames(sty.img___6Kim7)}
                                displayHeight={"400px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"400px"}
                                loading={"lazy"}
                                src={{
                                  src: corinneKutzTMi2R5NfoUnsplashjpgXcdVvFVkT2X8J6,
                                  fullWidth: 1920,
                                  fullHeight: 1280,
                                  aspectRatio: undefined,
                                }}
                              />
                            </div>
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"container5"}
                    data-plasmic-override={overrides.container5}
                    className={classNames(projectcss.all, sty.container5)}
                  >
                    <div
                      data-plasmic-name={"outerRow3"}
                      data-plasmic-override={overrides.outerRow3}
                      className={classNames(projectcss.all, sty.outerRow3)}
                    >
                      <div
                        data-plasmic-name={"row4"}
                        data-plasmic-override={overrides.row4}
                        className={classNames(projectcss.all, sty.row4)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__e0Gky
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img___6MeDx)}
                            displayHeight={"400px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"400px"}
                            loading={"lazy"}
                            src={{
                              src: tiffanyTertipesNxcs8Wwj9J0Unsplashjpg7YXw56Ww6R9OSh,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined,
                            }}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__aJWhy
                          )}
                        >
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__x1Ql7
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___7Zxl3
                                )}
                              />

                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__zfHCd
                                )}
                              >
                                {"Some value proposition of your service."}
                              </h3>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__cn9MH
                                )}
                              >
                                {
                                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                                }
                              </div>

                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button__eMxIl
                                )}
                                color={"blue"}
                                endIcon={
                                  <ArrowRightsvgIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg___7NDt8
                                    )}
                                    role={"img"}
                                  />
                                }
                                shape={"rounded"}
                                showEndIcon={true}
                              >
                                {"Learn more"}
                              </Button>
                            </p.Stack>
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"container6"}
                    data-plasmic-override={overrides.container6}
                    className={classNames(projectcss.all, sty.container6)}
                  >
                    <div
                      data-plasmic-name={"outerRow4"}
                      data-plasmic-override={overrides.outerRow4}
                      className={classNames(projectcss.all, sty.outerRow4)}
                    >
                      <div
                        data-plasmic-name={"row3"}
                        data-plasmic-override={overrides.row3}
                        className={classNames(projectcss.all, sty.row3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__cQd2R
                          )}
                        >
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__xAbe
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__unLg3
                                )}
                              />

                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__qA8J
                                )}
                              >
                                {"Some value proposition of your service."}
                              </h3>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___7JYu5
                                )}
                              >
                                {
                                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                                }
                              </div>

                              <Button
                                className={classNames(
                                  "__wab_instance",
                                  sty.button__ztlCy
                                )}
                                color={"blue"}
                                endIcon={
                                  <ArrowRightsvgIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__he3Pc
                                    )}
                                    role={"img"}
                                  />
                                }
                                shape={"rounded"}
                                showEndIcon={true}
                              >
                                {"Learn more"}
                              </Button>
                            </p.Stack>
                          ) : null}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__z3Gk
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__zaZr)}
                            displayHeight={"400px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"400px"}
                            loading={"lazy"}
                            src={{
                              src: xpsOcAuPlfZxEcUnsplashjpgILfqgGwTm1KB,
                              fullWidth: 640,
                              fullHeight: 360,
                              aspectRatio: undefined,
                            }}
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            ) : null}

            <section
              data-plasmic-name={"testimonials"}
              data-plasmic-override={overrides.testimonials}
              className={classNames(projectcss.all, sty.testimonials)}
            >
              <div className={classNames(projectcss.all, sty.column__eyzxd)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__oukYt
                  )}
                >
                  {"Testimonials"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mNk2R
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                  }
                </div>

                <div className={classNames(projectcss.all, sty.columns__zJoOb)}>
                  <div
                    className={classNames(projectcss.all, sty.column__vdGk2)}
                  >
                    <Testimonial
                      data-plasmic-name={"testimonial"}
                      data-plasmic-override={overrides.testimonial}
                      className={classNames("__wab_instance", sty.testimonial)}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__scusx)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__azIqs)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___1X1Gr
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__jfqkp)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: mepngKNmo8AmFIoYx9Z,
                            fullWidth: 140,
                            fullHeight: 140,
                            aspectRatio: undefined,
                          }}
                        />

                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__gEdqJ
                          )}
                        >
                          {"Zulia Maron Duo"}
                        </h5>

                        <div
                          before={""}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___2DZg
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                          }
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__vsEw6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___6YXlt
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___4Vp35
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__osUpx
                          )}
                        >
                          {"“"}
                        </h2>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__adsnM
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                          }
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns__vcx25
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__bue2E
                            )}
                          >
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img___1BjL)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: thumbAvatar1583758683JpgJc4NK1H4FWikX,
                                fullWidth: 160,
                                fullHeight: 160,
                                aspectRatio: undefined,
                              }}
                            />
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column___0UKxz
                            )}
                          >
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__v19A6
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h5>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {[2, 3, 4].map((currentItem, currentIndex) => (
              <BlogPosts
                data-plasmic-name={"blogPosts"}
                data-plasmic-override={overrides.blogPosts}
                className={classNames("__wab_instance", sty.blogPosts)}
              />
            ))}

            {true ? (
              <CtaBlock
                data-plasmic-name={"ctaBlock"}
                data-plasmic-override={overrides.ctaBlock}
                className={classNames("__wab_instance", sty.ctaBlock)}
              />
            ) : null}

            <HeroSection
              data-plasmic-name={"heroSection"}
              data-plasmic-override={overrides.heroSection}
              className={classNames("__wab_instance", sty.heroSection)}
            />

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </p.Stack>
        ) : null}
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "header2",
    "h1",
    "features",
    "container4",
    "outerRow2",
    "row2",
    "container5",
    "outerRow3",
    "row4",
    "container6",
    "outerRow4",
    "row3",
    "testimonials",
    "testimonial",
    "blogPosts",
    "ctaBlock",
    "heroSection",
    "footer",
  ],

  header2: ["header2"],
  h1: ["h1"],
  features: [
    "features",
    "container4",
    "outerRow2",
    "row2",
    "container5",
    "outerRow3",
    "row4",
    "container6",
    "outerRow4",
    "row3",
  ],

  container4: ["container4", "outerRow2", "row2"],
  outerRow2: ["outerRow2", "row2"],
  row2: ["row2"],
  container5: ["container5", "outerRow3", "row4"],
  outerRow3: ["outerRow3", "row4"],
  row4: ["row4"],
  container6: ["container6", "outerRow4", "row3"],
  outerRow4: ["outerRow4", "row3"],
  row3: ["row3"],
  testimonials: ["testimonials", "testimonial"],
  testimonial: ["testimonial"],
  blogPosts: ["blogPosts"],
  ctaBlock: ["ctaBlock"],
  heroSection: ["heroSection"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps,
        }),

      [props, nodeName]
    )

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage"
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`
  }
  return func
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header2: makeNodeComponent("header2"),
    h1: makeNodeComponent("h1"),
    features: makeNodeComponent("features"),
    container4: makeNodeComponent("container4"),
    outerRow2: makeNodeComponent("outerRow2"),
    row2: makeNodeComponent("row2"),
    container5: makeNodeComponent("container5"),
    outerRow3: makeNodeComponent("outerRow3"),
    row4: makeNodeComponent("row4"),
    container6: makeNodeComponent("container6"),
    outerRow4: makeNodeComponent("outerRow4"),
    row3: makeNodeComponent("row3"),
    testimonials: makeNodeComponent("testimonials"),
    testimonial: makeNodeComponent("testimonial"),
    blogPosts: makeNodeComponent("blogPosts"),
    ctaBlock: makeNodeComponent("ctaBlock"),
    heroSection: makeNodeComponent("heroSection"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
  }
)

export default PlasmicHomepage
/* prettier-ignore-end */
